# Generated by Django 6.0.7 on 2026-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='imap_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
