# Generated by Django 6.0.7 on 2026-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemsettings_imap_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='api_key',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
