# Generated by Django 6.0.7 on 2026-07-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoryrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_due_date', models.DateField()),
                ('frequency', models.CharField(default='MONTHLY', max_length=50)),
                ('is_auto_detected', models.BooleanField(default=False)),
            ],
        ),
    ]
