# Generated by Django 6.0.7 on 2026-07-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recurringbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
