# Generated by Django 6.0.7 on 2026-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_systemsettings_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_custom_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_model_mode',
            field=models.CharField(default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_model_tier',
            field=models.CharField(default='fast', max_length=20),
        ),
    ]
