# Generated by Django 6.0.7 on 2026-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemsettings_ai_custom_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
