# Generated by Django 6.0.7 on 2026-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_due_day_account_statement_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='pin_code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
